### PR TITLE
Detect canvas links that include dashes

### PR DESCRIPTION
**Pull request by GeorgeHahn**
This PR adds support for canvas video links with dashes in the filename.

Example song: https://open.spotify.com/track/4esxro8J1rbsalCPb0yrgC?si=82rTqJQ8TyWmxt0SQqrqqw

Associated canvas: https://canvaz.scdn.co/upload/artist/7yxi31szvlbwvKq9dYOmFI/video/606438b3-a9fe-4a88-8162-0bafd90cb2e6.cnvs.mp4

### CODE REVIEW

**Comment by GeorgeHahn** [comment]
I found that there are a few other canvas URI formats. Added support & examples in 298a6f3.

**Comment by itsmeow** [comment]
Nice! Thanks for this PR!

**Comment by GeorgeHahn** [comment]
Absolutely! Thank you for all of your work on this extension! I'm loving canvas on the desktop 😄

**Comment by itsmeow** [comment]
Good news: this is no longer needed as I've rewritten it to fully send/receive binary data from the endpoint.
Also supports the new UI / Spicetify-CLI 2.0.0.
Check it out: 19719f3076c1452208b0f73293e29b43c5d372a4

**Comment by GeorgeHahn** [comment]
Awesome work!! I haven't tried spicetify-cli 2.0.0 yet, looks like I'll have a bit of theming to do when the new UI arrives.

**Pull request merged**
